// Ready-made looks are cosmetic instructions, never a portrait/hairstyle prompt.
export const MAKEUP_LOOKS=[
 {id:'female-korean',gender:'female',name:'เกาหลีละมุน',description:'ชมพูละมุน ผิวสดใส',recommended:true,instruction:'Korean soft pink-peach makeup: softly define existing brow hairs without changing brow shape; delicate rose-peach eyelid tint and fine natural lash definition; diffused pink cheek blush; sheer soft rose-pink lips with gently diffused pigment within the original lip boundary; restrained radiant skin finish with visible pores'},
 {id:'female-clear',gender:'female',name:'หน้าใสธรรมชาติ',description:'บางเบา ดูเป็นธรรมชาติ',instruction:'Very light no-makeup makeup: retain original natural brows, almost no eyelid pigment, delicate existing lash definition, barely perceptible healthy cheek warmth and original-lip-colour rosy balm; fresh natural skin texture with minimal sheen and no artificial whitening'},
 {id:'female-soft-glam',gender:'female',name:'ฝอซอฟต์แกลม',description:'ตาน้ำตาล ปากนู้ดกุหลาบ',instruction:'Restrained Western soft glam: refine existing brow-hair definition without changing brow geometry; soft brown-taupe eyelid shading, fine defined liner following the original upper lash line and neatly separated lashes without enlarged eyes; muted nude-rose lips; softly blended bronze-rose blush; satin skin illumination, no sculpting or face contour reshaping'},
 {id:'female-douyin',gender:'female',name:'โต่วอิน',description:'ตาละมุน ปากไล่สี',instruction:'Wearable Douyin-inspired makeup for an ID photo: delicate peach-rose eyelid colour, tiny restrained inner-corner light and fine separated lash definition; soft rosy blush; rose-red gradient lip pigment concentrated toward the centre within the original lip contour; subtle luminous skin. Never enlarge eyes, add doll-like geometry, draw new under-eye folds, change iris colour or apply heavy glitter'},
 {id:'female-peach',gender:'female',name:'พีชสดใส',description:'พีชคอรัล สดชื่น',instruction:'Fresh peach makeup: softly groom existing eyebrow hairs, warm peach-coral eyelid tint, fine delicate upper lash definition, soft peach cheek blush and sheer peach-coral lips; a subtle healthy skin glow with intact pores and natural original complexion'},
 {id:'female-rose',gender:'female',name:'โรสสุภาพ',description:'กุหลาบตุ่น เรียบร้อย',instruction:'Professional muted rose makeup: softly define existing brow hairs; subtle rosy-brown eyelid shading and fine natural lashes; delicate dusty-rose cheeks and muted rose lips; restrained satin skin finish with real texture. Suitable for a formal job application portrait, without heavy cosmetics'},
 {id:'male-natural',gender:'male',name:'ธรรมชาติ',description:'สะอาด ไม่เห็นเมคอัพ',instruction:'Extremely subtle masculine no-makeup grooming: tidy tonal definition of existing brow hairs; retain original eyes, lashes and skin character; gently balance dull low-frequency skin tone and a barely perceptible original-lip-colour healthy tint. No visible lipstick, eyeshadow, heavy blush or whitening'},
 {id:'male-fresh',gender:'male',name:'สดใสสตูดิโอ',description:'สดชื่น สุขภาพดี',instruction:'Natural masculine studio grooming: fine definition of existing brow and lash hairs without changing geometry; fresh subtle healthy cheek colour and barely perceptible natural lip warmth; restrained luminous skin illumination with original complexion and intact pores. No feminine heavy eye makeup or obvious lipstick'},
 {id:'male-matte',gender:'male',name:'คมสุภาพ',description:'ลดมัน ดูสุภาพ',instruction:'Clean masculine matte professional grooming: reduce only excessive low-frequency oily shine, retain skin microtexture and natural facial highlights; softly define existing eyebrow hairs and original upper lash line, muted natural lip finish and extremely light natural cheek warmth. No facial contouring, reshaping, heavy cosmetics or beard changes'},
].map(look=>({...look,preview:'/assets/makeup/looks/'+look.id+'.webp'}));
export function makeupLook(id){return MAKEUP_LOOKS.find(look=>look.id===id)||null}

// Shared allowlist: the client cannot submit arbitrary AI prompts.
export const MAKEUP_TABS=[['brows','คิ้ว'],['lips','ลิปสติก'],['cheeks','แก้ม'],['lashes','ขนตา'],['blush','บลัช']];
export const MAKEUP_PRESETS={
 brows:[['natural','ธรรมชาติ','soft natural dark-brown eyebrows, retain individual brow hairs'],['straight','ทรงตรง','neatly groomed soft straight brown eyebrows'],['arched','โก่งนุ่ม','refined softly arched dark-brown eyebrows']],
 lips:[['rose','ชมพูกุหลาบ','sheer rose-pink lipstick'],['nude','พีชนู้ด','warm peach-nude lipstick'],['berry','เบอร์รี','muted berry satin lipstick']],
 cheeks:[['healthy','ผิวสุขภาพดี','a subtle healthy sheen on cheek skin'],['dewy','ผิวฉ่ำ','restrained dewy cheek glow, not greasy'],['highlight','ไฮไลต์นุ่ม','soft luminous highlight on the upper cheeks']],
 lashes:[['natural','ธรรมชาติ','natural defined black upper eyelashes'],['curl','งอนนุ่ม','softly curled fine upper eyelashes'],['airy','ยาวละมุน','fine airy slightly longer upper eyelashes, not false-lash strips']],
 blush:[['rose','ชมพู','subtle soft rose-pink cheek blush'],['peach','พีช','subtle warm peach cheek blush'],['coral','คอรัล','subtle muted coral cheek blush']]
};
export function validateMakeupStyles(value){
 if(!value||typeof value!=='object'||Array.isArray(value))throw Error('กรุณาเลือกเมคอัพ');
 if('look' in value){if(Object.keys(value).length!==1||typeof value.look!=='string'||!makeupLook(value.look))throw Error('โทนเมคอัพไม่ถูกต้อง');return {look:value.look}}
 const styles={};
 for(const [key,id] of Object.entries(value)){
  if(!MAKEUP_PRESETS[key]||typeof id!=='string'||!MAKEUP_PRESETS[key].some(p=>p[0]===id))throw Error('ตัวเลือกเมคอัพไม่ถูกต้อง');
  styles[key]=id;
 }
 if(!Object.keys(styles).length)throw Error('กรุณาเลือกเมคอัพอย่างน้อย 1 แบบ');
 return styles;
}
export function makeupPrompt(styles){
 styles=validateMakeupStyles(styles);
 if(styles.look)return `Retouch the EXACT supplied person with this ONE complete makeup look: ${makeupLook(styles.look).instruction}. Apply the coordinated brow, eyelid/lash, lip, cheek and skin cosmetic finish together in this single edit. Adapt pigment intensity to the original complexion; never whiten skin or change the person. Match the already processed skin seamlessly: sheer pigment integrated into existing skin, not an opaque foundation mask. Preserve original skin texture and facial illumination. Keep cosmetic changes gently diffused toward the hairline, temples and jaw, matching the unchanged ears and neck in base complexion and exposure. No abrupt complexion border, uniform painted face, exaggerated shiny patches or broad whitening. Blush remains localized, softly graduated and restrained; do not spread redness across the whole face. Preserve facial identity, geometry, expression, original brow and eye shape, eye spacing, iris, nose, lip boundary, jaw and chin, skin pores, freckles and identifying marks. Keep hair, hairstyle, hairline, ears, neck, shoulders, clothes, background, lighting direction, orientation, framing and proportions exactly unchanged. No mirroring, face slimming, eye enlargement, nose shaping, skin blur, artificial pore patterns, new collar or accessories. Makeup colour and low-frequency cosmetic sheen only; no new portrait or hairstyle. Return ONE image with the same aspect ratio and composition as the input.`;
 return `Retouch the EXACT supplied portrait with ONLY these makeup effects: ${Object.entries(styles).map(([key,id])=>MAKEUP_PRESETS[key].find(p=>p[0]===id)[2]).join('; ')}. Preserve the subject's identity, facial structure, eye shape, iris and eye color, nose, mouth shape, expression, head orientation, skin tone and real pores. Keep all unselected makeup areas unchanged. Do not smooth or regenerate the entire face. Keep hair, hairline, ears, neck, shoulders, clothes, background, lighting, framing, proportions and image orientation unchanged. No new collar, no mirroring, no accessories. Makeup must be subtle, realistic and suitable for an ID portrait. Return ONE image with the same composition and aspect ratio as the input.`;
}
