import React,{useEffect,useRef,useState} from 'react';
import './password-reset.css';
export function PasswordReset(){
 const [open,setOpen]=useState(false),[token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[done,setDone]=useState(false);const panel=useRef(null);
 useEffect(()=>{const hash=new URLSearchParams(location.hash.slice(1)),raw=hash.get('reset_password');if(raw){setToken(raw);setOpen(true);history.replaceState({},'',location.pathname+location.search)}const show=()=>{setToken('');setMessage('');setDone(false);setOpen(true)};window.addEventListener('idprom-forgot-password',show);return()=>window.removeEventListener('idprom-forgot-password',show)},[]);
 useEffect(()=>{if(open)panel.current?.querySelector('input,button')?.focus()},[open]);
 const close=()=>{if(busy)return;setOpen(false);setToken('');setPassword('');setConfirm('');setMessage('');setDone(false)};
 const submit=async e=>{e.preventDefault();if(busy||done)return;if(token&&password!==confirm){setMessage('รหัสผ่านทั้งสองช่องไม่ตรงกัน');return}setBusy(true);setMessage('');try{const r=await fetch('/api/auth/'+(token?'reset-password':'forgot-password'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(token?{token,password}:{email})});const data=await r.json();if(!r.ok)throw Error(data.message||'ดำเนินการไม่สำเร็จ');setMessage(data.message);setDone(true);setPassword('');setConfirm('')}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 if(!open)return null;
 return <div className="idprom-password-overlay" onKeyDown={e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const items=[...panel.current.querySelectorAll('input:not(:disabled),button:not(:disabled)')];if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus()}}}}><section ref={panel} className="idprom-password-card" role="dialog" aria-modal="true" aria-labelledby="idprom-password-title"><button className="idprom-password-close" disabled={busy} onClick={close} aria-label="ปิด">×</button><strong>IDพร้อม</strong><h2 id="idprom-password-title">{token?'ตั้งรหัสผ่านใหม่':'ลืมรหัสผ่าน'}</h2><p>{token?'ตั้งรหัสใหม่เพื่อเข้าสู่บัญชีเดิม เครดิตและงานที่บันทึกยังอยู่ครบ':'กรอกอีเมลที่สมัครไว้ เพื่อรับลิงก์ตั้งรหัสผ่านใหม่'}</p><form onSubmit={submit}>{!done&&(token?<><label>รหัสผ่านใหม่<input type="password" autoComplete="new-password" minLength={8} maxLength={128} required disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>ยืนยันรหัสผ่านใหม่<input type="password" autoComplete="new-password" minLength={8} maxLength={128} required disabled={busy} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></>:<label>อีเมล<input type="email" autoComplete="email" maxLength={254} required disabled={busy} value={email} onChange={e=>setEmail(e.target.value)}/></label>)}{message&&<p className="idprom-password-message" role="status">{message}</p>}{done?<button type="button" className="idprom-password-submit" onClick={close}>กลับไปเข้าสู่ระบบ</button>:<button className="idprom-password-submit" disabled={busy}>{busy?'กำลังดำเนินการ…':token?'บันทึกรหัสผ่านใหม่':'ส่งลิงก์ทางอีเมล'}</button>}{token&&!done&&<button type="button" className="idprom-password-again" disabled={busy} onClick={()=>{setToken('');setMessage('');setPassword('');setConfirm('')}}>ขอลิงก์ใหม่</button>}</form></section></div>;
}
