import React,{useRef,useEffect} from 'react';
import {StudioToolIcon} from './studio-icons.jsx';
export const partName=l=>l?.name==='หัว · คอ · ผม'?'หัวและผม':l?.name||'เลือกส่วนที่ต้องการปรับ';
function TouchValueControl({keyName,label,min,max,step,value,change,remember}){
 const latest=useRef(value);useEffect(()=>{latest.current=value},[value]);
 const update=(v,record)=>{latest.current=v;change({[keyName]:v},record)};
 const stepValue=direction=>{const next=Math.max(min,Math.min(max,+(latest.current+direction*step).toFixed(2)));if(next!==latest.current)update(next,true)};
 const display=keyName==='scale'||keyName==='opacity'?Math.round(value*100)+'%':Math.round(value)+(keyName==='rotation'?'°':' px');
 return <label><span>{label}</span><button aria-label={'ลด'+label} disabled={value<=min} onClick={()=>stepValue(-1)}>−</button><input aria-label={'ปรับ'+label} type="range" min={min} max={max} step={step} value={value} onPointerDown={remember} onKeyDown={e=>{if(e.key.startsWith('Arrow')||e.key==='Home'||e.key==='End')remember()}} onChange={e=>update(+e.target.value,false)}/><button aria-label={'เพิ่ม'+label} disabled={value>=max} onClick={()=>stepValue(1)}>+</button><output>{display}</output></label>;
}
export function TouchParts({layers,selected,onSelect,disabled,thumbnails,attention}){
 return <section className={'studio-touch-parts'+(attention?' studio-layer-attention':'')} aria-label="เลือกส่วนที่ต้องการปรับ"><div className="studio-touch-part-row"><div className="studio-touch-part-rail"><button aria-label="ไม่เลือกเลเยอร์" aria-pressed={!selected} className={!selected?'active':''} disabled={disabled} onClick={()=>onSelect(null)}><StudioToolIcon kind="none"/><span>ไม่เลือก</span></button>{[...layers].sort((a,b)=>(a.name==='พื้นหลัง')-(b.name==='พื้นหลัง')).map(l=><button key={l.id} aria-label={'ปรับ '+partName(l)} aria-pressed={l.id===selected} className={l.id===selected?'active':''} disabled={disabled} onClick={()=>onSelect(l.id)}><img src={thumbnails[l.id]||l.source} alt=""/><span>{partName(l)}</span>{l.id===selected&&<b>✓</b>}{l.locked&&<small>🔒</small>}{!l.visible&&<small>ซ่อน</small>}</button>)}</div></div></section>
}
export function TouchAdjust({onChooseTool,current,open,setOpen,tab,setTab,side,setSide,change,remember,disabled,warped,more,setMore}){
 const collar=Boolean(current?.collarParts),name=partName(current);
 const fields=tab==='position'?(collar&&side!=='both'?[[side==='left'?'collarLeftX':'collarRightX','ซ้าย–ขวา',-300,300,1]]:[['x','ซ้าย–ขวา',-900,900,1],['y','ขึ้น–ลง',-1200,1200,1]]):tab==='scale'?[['scale','ขนาด',.1,3,.01]]:tab==='rotation'?[['rotation','หมุน',-180,180,1]]:[['opacity','ความทึบ',0,1,.01]];
 const locked=disabled||!current||current.locked||!current.visible||(collar&&side!=='both'&&tab==='position'&&warped);
 const format=(k,v)=>k==='scale'||k==='opacity'?Math.round(v*100)+'%':Math.round(v)+(k==='rotation'?'°':' px');
 return <section className="studio-touch-adjust" aria-label="ปรับแต่งส่วนที่เลือก">{onChooseTool&&<button className="studio-change-tools" onClick={onChooseTool}>เปลี่ยนเครื่องมือ</button>}<button className="studio-touch-sheet-heading" aria-label={open?'ย่อแผงปรับแต่ง':'เปิดแผงปรับแต่ง'} aria-expanded={open} onClick={()=>{setOpen(!open);setMore(false)}}><b aria-hidden="true">{open?'⌄':'⌃'}</b></button>{open&&<><div className="studio-touch-adjust-tabs" role="tablist" aria-label="ค่าที่ต้องการปรับ">{[['position','ตำแหน่ง'],['scale','ขนาด'],['rotation','หมุน'],['opacity','ความทึบ']].map(([id,label])=><button role="tab" aria-selected={tab===id&&!more} key={id} className={tab===id&&!more?'active':''} onClick={()=>{setTab(id);setMore(false)}}>{label}</button>)}<button className={more?'active':''} aria-expanded={more} onClick={()=>setMore(more?false:'layers')}>เพิ่มเติม</button></div>{!more&&<>{collar&&tab==='position'&&<div className="studio-touch-sides" aria-label="เลือกด้านของเข็ม">{[['both','ทั้งคู่'],['left','ซ้าย'],['right','ขวา']].map(([id,label])=><button key={id} aria-pressed={side===id} className={side===id?'active':''} onClick={()=>setSide(id)}>{label}</button>)}</div>}<fieldset className="studio-touch-controls" disabled={locked}>{fields.map(([key,label,min,max,step])=>{const v=current?.[key]??(key==='scale'||key==='opacity'?1:0);return <TouchValueControl key={key} keyName={key} label={label} min={min} max={max} step={step} value={v} change={change} remember={remember}/>})}<button className="studio-touch-reset" onClick={()=>change(collar&&side!=='both'&&tab==='position'?{[side==='left'?'collarLeftX':'collarRightX']:0}:Object.fromEntries(fields.map(([k])=>[k,k==='scale'||k==='opacity'?1:0])))}>รีเซ็ต</button></fieldset>{current?.locked&&<p>ส่วนนี้ล็อกอยู่ · ปลดล็อกใน “เพิ่มเติม” เพื่อปรับ</p>}{!current?.visible&&current&&<p>ส่วนนี้ซ่อนอยู่ · เปิดการแสดงใน “เพิ่มเติม”</p>}{warped&&collar&&side!=='both'&&tab==='position'&&<p>คืนรูปก่อนบิดใน “เพิ่มเติม” เพื่อเลื่อนเข็มแยกด้าน</p>}</>}</>}</section>
}
